### ISSUE TITLE
`e.data` vs. `e.control.data`

### ISSUE THREAD

**Issue by rusty-snake** [flet-dev/website#236]
https://github.com/flet-dev/website/blob/2eed1d3f9bcec3019b17133af84c3fa6b0fe1cf2/docs/tutorials/python-calculator.md?plain=1#L217

`e.data` is always an empty string. `e.control.data` gives you the expected value.

**Comment by ndonkoHenri** [comment]
That's true! Will you like to make a PR with the correct code?

**Comment by rusty-snake** [comment]
Looks like this is the only occurrences of [`e.data`](https://github.com/search?q=repo%3Aflet-dev%2Fwebsite%20e.data&type=code) that should be `e.control.data`.
