### ISSUE TITLE
Is it okay adding image preview under code sections?

### ISSUE THREAD

**Issue by techemmy** [flet-dev/website#47]

**Comment by FeodorFitsner** [comment]
What do you mean?

**Comment by ndonkoHenri** [comment]
Do you mean Screenshots for Flet's [online docs page](https://flet.dev/docs/controls) on controls ?

**Comment by techemmy** [comment]
I mean screenshots for the [online docs python guide](https://flet.dev/docs/guides/python/getting-started) codes.

**Comment by ndonkoHenri** [comment]
I had the same idea.
I made a PR. https://github.com/flet-dev/website/pull/46

Maybe you could add those I didn't.

(There seems to be conflicts with the PR. Can you help me ? 😅)

**Comment by techemmy** [comment]
Sure. I want to confirm with @FeodorFitsner before I start anything on it.

**Comment by FeodorFitsner** [comment]
Sure, that would be nice!

**Comment by techemmy** [comment]
Alright, I'll be on that. @ndonkoHenri you can also add images to make it faster. I'm already working on the Python Guide getting started
