### ISSUE TITLE
ft.MainAxisAlignment and so on replacement

### ISSUE THREAD

**Issue by RezaOptimotive** [flet-dev/website#77]
I'm not exactly sure how deep this problem goes, but what I've noticed is that ft.MainAxisAlignment.CENTER which is used in the documentation gives an error. And looking at the examples repo, I noticed it's mostly been with a string of "center". 

This unfortunately made me really question if I want to go down the road of learning Flet. And honestly, I'm glad I gave it the time to figure out this problem, coz honestly it's a great framework. And I'm just mentioning this as it could really damage the onboarding of new developers.

This issue is also exasperated by Github Copilot

**Comment by FeodorFitsner** [comment]
Could you please share a code sample demonstrating the issue?

**Comment by RezaOptimotive** [comment]
for me this gives me the error `module flet does not have attribute MainAxisAlignment`



    import flet as ft

    def main(page: ft.Page):
        page.title = "Flet counter example"
        page.vertical_alignment = ft.MainAxisAlignment.CENTER

        txt_number = ft.TextField(value="0", text_align=ft.TextAlign.RIGHT, width=100)

        def minus_click(e):
            txt_number.value = str(int(txt_number.value) - 1)
            page.update()

        def plus_click(e):
            txt_number.value = str(int(txt_number.value) + 1)
            page.update()

        page.add(
            ft.Row(
                [
                    ft.IconButton(ft.icons.REMOVE, on_click=minus_click),
                    txt_number,
                    ft.IconButton(ft.icons.ADD, on_click=plus_click),
                ],
                alignment=ft.MainAxisAlignment.CENTER,
            )
        )

    ft.app(target=main)


and changing the second line in the main function to `page.vertical_alignment = "center"` creates the effect that the demo demonstrates and resolves the issue.

alignment at the end of the method function inside the `Row` component also gives the error which needs to be change to the string `"center"`

I have noticed that the code in the examples repository runs error-free, but the documentation in the website is not consistent with those code examples.

**Comment by RezaOptimotive** [comment]
My apologies, you're right. I'm not sure how this happened as I did run `pip install flet` just about 2 weeks ago or so.
