### ISSUE TITLE
broken Link to elevatedbutton style

### ISSUE THREAD

**Issue by ndonkoHenri** [flet-dev/website#80]
From [this page](https://flet.dev/docs/controls/outlinedbutton#style), clicking the link in the description to the style prop of the elevated button says page not found. Tried to fix it, but what I saw in the markdown file seems alright:
--- See ElevatedButton.style](elevatedbutton#style)

Don't know where the issue is.. :)
Link to md file: https://github.com/flet-dev/website/blob/main/docs/controls/elevatedbutton.md

**Comment by FeodorFitsner** [comment]
It's been fixed. Try here: https://flet.dev/docs/controls/outlinedbutton#style
